gpu_id: '0'
log_wandb: True
wandb_project: 'Mamba4POI'
wandb_entity: "KactusJec" 
wandb_run_name: 'SINE_GWL' 
logging:
  level: DEBUG


embedding_size: 64              # (int) The input and output hidden size.
layer_norm_eps: 1e-12           # (float) The value added to the denominator for numerical stability.
prototype_size: 50              # (int) The size of latent prototypes.
interest_size: 3                # (int) The number of intentions.
tau_ratio: 0.1                  # (float) The tau value for temperature tuning.
reg_loss_ratio: 0.5             # (float) The L2 regularization weight.
loss_type: 'CE'                 # (str) The type of loss function. Range in ['BPR', 'CE'].

# Save Directory Settings
checkpoint_dir: 'SavedData'
save_dataloaders: False
dataloaders_save_path: ''  # 留空，代码会使用默认路径
save_dataset: True         # 启用保存dataset功能
dataset: gowalla
dataset_save_path: 'SavedData/gowalla.pth' 
seed: 42  # 设置一个默认种子
train_neg_sample_args:  null


#Dataset Settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: venue_id
TIME_FIELD: timestamp
LABEL_FIELD: label

load_col:
    inter: [user_id, venue_id,timestamp]
    item: [venue_id,latitude, longitude]

LIST_SUFFIX: "_list"
MAX_ITEM_LIST_LENGTH: 128
ITEM_LIST_LENGTH_FIELD: venue_seq_len


#Dataloader&Sampler

Use_CustomDataset: True  # 使用自定义的 FourSquareDataset 数据集类
Use_CustomSampler: False
repeatable: True  #进行阶段隔离
NEG_PREFIX: "neg_"



# training settings
epochs: 40
train_batch_size: 1024
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 4
single_spec: True

# train_neg_sample_args: 
#   distribution: "popularity"
#   alpha: 0.5
#   dynamic: False
#   sample_num: 5
train_neg_sample_args: ~ #CE

eval_args:
  order: TO 
  spilt: 
    RS: [0.7,0.1,0.2]
  gourp_by: user_id
  max_seq_len: 128 
  mode:
    val: full
    test: full




metrics: ['Recall', 'MRR','NDCG','ItemCoverage','AveragePopularity','TailPercentage']
valid_metric: NDCG@10
eval_batch_size: 1024
weight_decay: 0
topk: [1,5,10,20]
tail_ratio: 0.15






